Databricks Support
flyway/flyway-community-db-support pull request #26
Opened 2024-02-21 05:46 UTC by tdimhcsleumas

This change ports this pr:  https://github.com/flyway/flyway/pull/3681

2024-02-28 15:48 UTC, Barry-RG reviewed
Thank you for porting this change to this repository. 
I have left a couple of review comments to do before merging.

If you have any documentation you could point us to to allow us to smoke test this integration, that would be appreciated.

2024-02-28 15:48 UTC, Barry-RG commented on flyway-database-databricks/src/main/resources/META-INF/services/org.flywaydb.core.extensibility.Plugin
> +org.flywaydb.community.database.CommunityDatabaseExtension
These classes are not part of this module and should not be included here.

2024-02-28 15:48 UTC, Barry-RG commented on pom.xml
> +
Can you remove this unnecessary new line

2024-02-28 15:49 UTC, Barry-RG requested changes
My previous comment was meant to be a change request.

2024-02-29 20:03 UTC, tdimhcsleumas commented on flyway-database-databricks/src/main/resources/META-INF/services/org.flywaydb.core.extensibility.Plugin
> +org.flywaydb.community.database.CommunityDatabaseExtension
Will do!

2024-03-01 10:06 UTC, Barry-RG requested changes

2024-03-01 10:06 UTC, Barry-RG commented on flyway-database-databricks/pom.xml
> +        </dependency>
With the move to this repository this has lost its version. Could you please specify which version of the databricks driver is being used here.

2024-03-12 10:29 UTC, Barry-RG commented on flyway-database-databricks/pom.xml
> +        </dependency>
@tdimhcsleumas is there any update on this?

2024-03-12 12:00 UTC, tdimhcsleumas commented on flyway-database-databricks/pom.xml
> +        </dependency>
Hi, in the process of moving at the moment. Will set some time aside to apply updates in the few days.

2024-04-26 02:36 UTC, skitscha commented
Can this be merged in now?

2024-04-30 10:27 UTC, Barry-RG commented
cc: @tdimhcsleumas @skitscha 
We are currently in the process of trying to test this integration with Databricks and Flyway.

2024-04-30 10:29 UTC, Barry-RG commented
cc: @tdimhcsleumas @skitscha 
We are currently in the process of trying to test this integration with Databricks and Flyway. 
If you have any tests or test cases that could help expedite this PR

2024-05-02 16:42 UTC, skitscha1 commented
I should be able to help test this integration but the build is failing and I cannot contribute to this branch to fix it. @tdimhcsleumas Can you resolve the build issue?

2024-05-02 23:41 UTC, tdimhcsleumas commented
@skitscha1 yes. I'll set aside some time in the next few days to fix it.

2024-05-03 10:28 UTC, piers-williams requested changes
I've taken a look and here are changes that needed to be made to get this building

2024-05-03 10:28 UTC, piers-williams commented on flyway-database-databricks/src/main/java/org/flywaydb/community/database/DatabricksDatabaseExtension.java
> +                    IgniteDatabaseExtension.class.getClassLoader().getResourceAsStream("org/flywaydb/community/database/databricks/version.txt"),
```suggestion
                    DatabricksDatabaseExtension.class.getClassLoader().getResourceAsStream("org/flywaydb/community/database/databricks/version.txt"),
```

2024-05-03 10:28 UTC, piers-williams commented on flyway-database-databricks/src/main/java/org/flywaydb/community/database/databricks/DatabricksTable.java
> +        this.insertRowLock = new InsertRowLock(jdbcTemplate, 10);
```suggestion
        this.insertRowLock = new InsertRowLock(jdbcTemplate);
```

2024-05-03 10:28 UTC, piers-williams commented on flyway-database-databricks/src/main/java/org/flywaydb/community/database/databricks/DatabricksDatabase.java
> +    }
```suggestion
    @Override
    public void ensureSupported(Configuration configuration) {
        // Always latest Databricks version.
    }
```

2024-05-03 10:28 UTC, piers-williams commented on flyway-database-databricks/src/main/java/org/flywaydb/community/database/databricks/DatabricksDatabase.java
> +    }
```suggestion
```

2024-05-03 10:28 UTC, piers-williams commented on flyway-database-databricks/src/main/java/org/flywaydb/community/database/databricks/DatabricksDatabaseType.java
> +public class DatabricksDatabaseType extends BaseDatabaseType {
```suggestion
public class DatabricksDatabaseType extends BaseDatabaseType implements CommunityDatabaseType {
```

2024-05-03 18:07 UTC, tdimhcsleumas commented
Thanks @piers-williams, I'll implement those changes shortly.

2024-05-03 18:23 UTC, tdimhcsleumas commented on flyway-database-databricks/src/main/java/org/flywaydb/community/database/databricks/DatabricksDatabaseType.java
> +public class DatabricksDatabaseType extends BaseDatabaseType {
Not sure about this one given none of the other database types implement `CommunityDatabaseType`.

2024-05-03 18:32 UTC, tdimhcsleumas commented
@skitscha @Barry-RG I ran `mvn -B install --file pom.xml` locally and got a successful build.

2024-05-07 08:01 UTC, piers-williams commented on flyway-database-databricks/src/main/java/org/flywaydb/community/database/databricks/DatabricksDatabaseType.java
> +public class DatabricksDatabaseType extends BaseDatabaseType {
They all do - it was added 2 months ago. Here is [Ignite](https://github.com/flyway/flyway-community-db-support/blob/6be5b41f1ccbe618b51991dba7f43e2f2f84581c/flyway-database-ignite/src/main/java/org/flywaydb/community/database/ignite/thin/IgniteThinDatabaseType.java#L40)  for reference

2024-05-07 08:04 UTC, tdimhcsleumas commented on flyway-database-databricks/src/main/java/org/flywaydb/community/database/databricks/DatabricksDatabaseType.java
> +public class DatabricksDatabaseType extends BaseDatabaseType {
My bad

2024-05-07 08:10 UTC, tdimhcsleumas commented on flyway-database-databricks/src/main/java/org/flywaydb/community/database/databricks/DatabricksDatabaseType.java
> +public class DatabricksDatabaseType extends BaseDatabaseType {
Updated

2024-05-07 08:24 UTC, piers-williams approved these changes

2024-05-08 09:27 UTC, Barry-RG approved these changes

2024-05-08 09:27 UTC, merged